version: '3.7'
services:
  cashless_postgres:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - "../Postgres/dbdata:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: cashless_postgres
    hostname: cashless_postgres
    environment:
      POSTGRES_USER: cashless_postgres_user
      POSTGRES_PASSWORD: 'YOUR_SECRET_HERE'
      POSTGRES_DB: cashless_postgres_db 

  cashless_django:
    image: cashless_django
    restart: always
    volumes:
      - "../DjangoFiles:/DjangoFiles"
    working_dir: /DjangoFiles/
    container_name: cashless_django
    hostname: cashless_django
    command: "bash /DjangoFiles/launch.sh"
    depends_on:
      - cashless_postgres
    links:
      - cashless_postgres

  cashless_nginx:
    image: nginx
    restart: always
    volumes:
      - "../DjangoFiles:/DjangoFiles"
      - "../Nginx:/etc/nginx/conf.d"
    ports :
      - 8000:80
    depends_on:
      - cashless_django

