version: '3'
services:
  cashlessoi_postgres:
    image: "postgres:9.6.2"
    volumes:
      - "../Postgres/dbdata:/var/lib/postgresql/data"
      - "../Postgres/SaveDb:/SaveDb"
      - "../Postgres/cron.sh:/cron.sh"
    container_name: cashlessoi_postgres
    hostname: cashlessoi_postgres
    environment:
      POSTGRES_USER: cashlessoi_postgres_user
      POSTGRES_PASSWORD: YOUR_SECRET_HERE
      POSTGRES_DB: cashlessoi_postgres_db 

  cashlessoi_django:
    image: cashlessoi_django
    volumes:
      - "../DjangoFiles:/DjangoFiles"
    working_dir: /DjangoFiles/
    container_name: cashlessoi_django
    hostname: cashlessoi_django
    command: "bash /DjangoFiles/launch.sh"
    depends_on:
      - cashlessoi_postgres
    links:
      - cashlessoi_postgres

  cashlessoi_nginx:
    image: nginx
    volumes:
      - "../DjangoFiles:/DjangoFiles"
      - "../Nginx:/etc/nginx/conf.d"
    ports :
      - 8000:80
    depends_on:
      - cashlessoi_django

