version: '3'
services:
  cashless_postgres:
    image: "cashless_postgres"
    restart: on-failure
    volumes:
      - "../Postgres/dbdata:/var/lib/postgresql/data"
      - "../Postgres/SaveDb:/SaveDb"
      - "../Postgres/cron.sh:/cron.sh"
    container_name: cashless_postgres
    hostname: cashless_postgres
    environment:
      POSTGRES_USER: cashless_postgres_user
      POSTGRES_PASSWORD: YOUR_SECRET_HERE
      POSTGRES_DB: cashless_postgres_db 

  cashless_django:
    image: cashless_django
    restart: on-failure
    volumes:
      - "../DjangoFiles:/DjangoFiles"
    working_dir: /DjangoFiles/
    container_name: cashless_django
    hostname: cashless_django
    command: "bash /DjangoFiles/launch.sh"
    depends_on:
      - cashless_postgres
    links:
      - cashless_postgres

  cashless_nginx:
    image: nginx
    restart: on-failure
    volumes:
      - "../DjangoFiles:/DjangoFiles"
      - "../Nginx:/etc/nginx/conf.d"
    ports :
      - 8000:80
    depends_on:
      - cashless_django

